package com.codinglance.mydinningmap.feature


// ─────────────────────────────────────────────────────────────────
//  SAMPLE DATA REPOSITORY
//  Replace with your real data source (Room DB / API / etc.)
// ─────────────────────────────────────────────────────────────────

// New Restaurant Data

object JourneyRepository {

    val sampleJourneys: List<Journey> = listOf(

        // ── Journey 1: Mumbai City Tour ───────────────────────────
        Journey(
            id = 1,
            name = "Gurgaon City",
            description = "A full day exploring the best of Mumbai",
            date = "Dec 15, 2024",
            coverEmoji = "🌆",
            totalDistanceKm = 34.6f,
            stops = listOf(
                JourneyStop(
                    id = 1,
                    title = "Haldiram",
                    address = "Sahara Mall Shopping Complex M.G.Raod,Gurugram",
                    notes = "Started early at 7am. Light traffic.",
                    latitude = 28.4794338,
                    longitude = 77.0864217,
                    date = "Jul 12, 2025 at 09:58 PM",
                    stopType = StopType.START,
                    distanceFromPrev = 0f,
                    durationAtStop = 5,
                    paid_amount = "₹ 288",
                    total_amount = "₹ 404",
                    discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/117/0.jpg?width=5000&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true,
                    is_prime = false
                ),
                JourneyStop(
                    id = 2,
                    title = "YouMee",
                    address = "Unit No GR-02, Ground Floor, Worldmark Gurgaon, Village Maidawas, Sector 65, Gurugram, Haryana – 122001",
                    notes = "Iconic colonial architecture. Very crowded in the morning but worth it. Watched boats leave for Elephanta.",
                    latitude = 28.3980361,
                    longitude = 77.0726711,
                    date = "Jun 08, 2025 at 12:48 PM",
                    stopType = StopType.PHOTO,
                    distanceFromPrev = 12.3f,
                    durationAtStop = 45,
                    paid_amount = "₹ 1124",
                    total_amount = "₹ 1836",
                    discount_amount = "₹ 712",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/687654/restaurant020230320081903.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/youmee-worldmark-4-sector-65-gurgaon-687654",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 3,
                    title = "Barista Coffee",
                    address = "Shop No.D1 And D13-Fround Floor, Dlf Phase Qutub Plaza, Gurugram",
                    notes = "Famous breakfast spot. Had keema pav and chai. Great vibes, old-school feel.",
                    latitude = 28.4714694,
                    longitude = 77.1020038,
                    date = "Dec 06, 2025 at 06:21 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 0.6f,
                    durationAtStop = 60,
                    paid_amount = "₹ 355",
                    total_amount = "₹ 609",
                    discount_amount = "₹ 254",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/552/menu020230111095005.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/barista-lavazza-espresso-bar-dlf-phase-1-120792",
                    is_chain = true,
                    is_prime = false
                ),
                JourneyStop(
                    id = 4,
                    title = "P.F. Chang",
                    address = "Unit No. 6, Ground Floor, DLF Phase 2, Sector 24, DLF Cyber City, Gurgaon",
                    notes = "Famous breakfast spot. Had keema pav and chai. Great vibes, old-school feel.",
                    latitude = 28.4950716,
                    longitude = 77.0884522,
                    date = "May 17, 2025 at 12:17 AM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 0.6f,
                    durationAtStop = 60,
                    paid_amount = "₹ 2791",
                    total_amount = "₹ 4677",
                    discount_amount = "₹ 1886",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/695156/restaurant020240514121719.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/pf-changs-cyber-hub-gurgaon-695156",
                    is_chain = false,
                    is_prime = true
                ),
                JourneyStop(
                    id = 5,
                    title = "Haldiram MGF Metropolitan Mall",
                    address = "MGF Metropolitan Mall, MG Road, Gurgaon",
                    notes = "Picked up fresh fruits and spices. Chaotic but fun experience. Got mangoes and cashews.",
                    latitude = 28.4809652,
                    longitude = 77.0803792,
                    date = "Jul 03, 2025 at 08:08 PM",
                    stopType = StopType.VISIT,
                    distanceFromPrev = 0.7f,
                    durationAtStop = 40,
                    paid_amount = "₹ 488",
                    total_amount = "₹ 659",
                    discount_amount = "₹ 171",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/117/0.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-global-foyer-mall-gurgaon-690568",
                    is_chain = true,
                    is_prime = false
                ),
                JourneyStop(
                    id = 6,
                    title = "Punjab Grill Tappa",
                    address = "Shop 19, Ground floor, DLF Cybercity, Gurgaon-122002",
                    notes = "Had their famous chicken sandwich and beer. Love the Mario Miranda murals on the walls.",
                    latitude = 28.4959442,
                    longitude = 77.0888396,
                    date = "Nov 06, 2025 at 02:42 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 3.2f,
                    durationAtStop = 75,
                    paid_amount = "₹ 2090",
                    total_amount = "₹ 3113",
                    discount_amount = "₹ 1023",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/643894/restaurant020210113062035.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/punjab-grill-tappa-cyber-hub-gurgaon-643894",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 7, title = "OMI by Aldott",
                    address = "The Aldott, 81, Moulsari Ave, DLF Phase 3, Sector 24, Gurugram, Haryana",
                    notes = "Walked the Queen's Necklace at golden hour. Beautiful sunset view. Sat at the sea wall for an hour.",
                    latitude = 28.492682,
                    longitude = 77.1076935,
                    date = "Nov 05, 2025 at 04:23 PM",
                    stopType = StopType.VISIT,
                    distanceFromPrev = 4.1f,
                    durationAtStop = 60,
                    paid_amount = "₹ 1822",
                    total_amount = "₹ 2588",
                    discount_amount = "₹ 766",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/696057/restaurant020240607113245.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/omi-by-aldott-dlf-phase-3-gurgaon-696057",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 8,
                    title = "My Secret Place",
                    address = "SCO 14, Main Palam Vihar Road, Palam Vihar, Sector 23A, Gurugram",
                    notes = "Quick coffee stop before heading home.",
                    latitude = 28.5049246,
                    longitude = 77.0527208,
                    date = "Oct 10, 2025 at 11:29 PM",
                    stopType = StopType.REST,
                    distanceFromPrev = 9.8f,
                    durationAtStop = 25,
                    paid_amount = "₹ 752",
                    total_amount = "₹ 969",
                    discount_amount = "₹ 217",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/683100/restaurant020220329071556.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/my-secret-place-palam-vihar-gurgaon-683100",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 9,
                    title = "The Drunken Botanist",
                    address = "Unit 1B & 1C, Upper Ground Floor-C, Building 10C, Cyber Hub, DLF Cyber City, Gurgaon",
                    notes = "Back home after an amazing day. Feet ache but memories made!",
                    latitude = 28.4938892,
                    longitude = 77.0883356,
                    date = "Jul 29, 2025 at 10:35 PM",
                    stopType = StopType.END,
                    distanceFromPrev = 1.8f,
                    durationAtStop = 0,
                    paid_amount = "₹ 5657",
                    total_amount = "₹ 7689",
                    discount_amount = "₹ 2032",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/653381/restaurant020180511132249.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/the-drunken-botanist-dlf-cyber-city-gurgaon-653381",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 10,
                    title = "Daryaganj",
                    address = "Ambience Mall DLF Phase 3, Haryana",
                    notes = "Back home after an amazing day. Feet ache but memories made!",
                    latitude = 28.5055767,
                    longitude = 77.0962019,
                    date = "Jul 22, 2025 at 04:02 PM",
                    stopType = StopType.END,
                    distanceFromPrev = 1.8f,
                    durationAtStop = 0,
                    paid_amount = "₹ 4453",
                    total_amount = "₹ 5343",
                    discount_amount = "₹ 890",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/671925/restaurant320201006084302.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/daryaganj-ambience-mall-gurgaon-671925",
                    is_chain = false,
                    is_prime = false
                )
            )
        )
    )
}