package com.codinglance.mydinningmap.feature

import com.codinglance.mydinningmap.feature.Journey


// ─────────────────────────────────────────────────────────────────
//  SAMPLE DATA REPOSITORY
//  Replace with your real data source (Room DB / API / etc.)
// ─────────────────────────────────────────────────────────────────

// New Restaurant Data

object JourneyRepository {

    val sampleJourneys: List<Journey> = listOf(

        // ── Journey 1: Gurgaon City Tour ─────────────────────────
        Journey(
            id = 1,
            name = "Gurgaon City",
            description = "A full day exploring the best of Gurgaon",
            date = "Dec 15, 2024",
            coverEmoji = "🌆",
            totalDistanceKm = 34.6f,
            stops = listOf(
                JourneyStop(
                    id = 1,
                    title = "Haldiram",
                    address = "Sahara Mall Shopping Complex M.G.Raod,Gurugram",
                    notes = "Started early at 7am. Light traffic.",
                    latitude = 28.4794338,
                    longitude = 77.0864217,
                    date = "Jul 12, 2025 at 09:58 PM",
                    stopType = StopType.START,
                    distanceFromPrev = 0f,
                    durationAtStop = 5,
                    paid_amount = "₹ 288",
                    total_amount = "₹ 404",
                    discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/117/0.jpg?width=5000&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true,
                    is_prime = false
                ),
                JourneyStop(
                    id = 2,
                    title = "YouMee",
                    address = "Unit No GR-02, Ground Floor, Worldmark Gurgaon, Sector 65, Gurugram",
                    notes = "Iconic colonial architecture. Very crowded in the morning but worth it.",
                    latitude = 28.3980361,
                    longitude = 77.0726711,
                    date = "Jun 08, 2025 at 12:48 PM",
                    stopType = StopType.PHOTO,
                    distanceFromPrev = 12.3f,
                    durationAtStop = 45,
                    paid_amount = "₹ 1124",
                    total_amount = "₹ 1836",
                    discount_amount = "₹ 712",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/687654/restaurant020230320081903.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/youmee-worldmark-4-sector-65-gurgaon-687654",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 3,
                    title = "Barista Coffee",
                    address = "Shop No.D1 And D13, DLF Phase, Qutub Plaza, Gurugram",
                    notes = "Famous breakfast spot. Had keema pav and chai. Great vibes, old-school feel.",
                    latitude = 28.4714694,
                    longitude = 77.1020038,
                    date = "Dec 06, 2025 at 06:21 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 0.6f,
                    durationAtStop = 60,
                    paid_amount = "₹ 355",
                    total_amount = "₹ 609",
                    discount_amount = "₹ 254",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/552/menu020230111095005.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/barista-lavazza-espresso-bar-dlf-phase-1-120792",
                    is_chain = true,
                    is_prime = false
                ),
                JourneyStop(
                    id = 4,
                    title = "P.F. Chang",
                    address = "Unit No. 6, Ground Floor, DLF Phase 2, Sector 24, Gurgaon",
                    notes = "Famous breakfast spot. Had keema pav and chai. Great vibes, old-school feel.",
                    latitude = 28.4950716,
                    longitude = 77.0884522,
                    date = "May 17, 2025 at 12:17 AM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 0.6f,
                    durationAtStop = 60,
                    paid_amount = "₹ 2791",
                    total_amount = "₹ 4677",
                    discount_amount = "₹ 1886",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/695156/restaurant020240514121719.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/pf-changs-cyber-hub-gurgaon-695156",
                    is_chain = false,
                    is_prime = true
                ),
                JourneyStop(
                    id = 5,
                    title = "Haldiram MGF Metropolitan Mall",
                    address = "MGF Metropolitan Mall, MG Road, Gurgaon",
                    notes = "Picked up fresh fruits and spices. Chaotic but fun experience.",
                    latitude = 28.4809652,
                    longitude = 77.0803792,
                    date = "Jul 03, 2025 at 08:08 PM",
                    stopType = StopType.VISIT,
                    distanceFromPrev = 0.7f,
                    durationAtStop = 40,
                    paid_amount = "₹ 488",
                    total_amount = "₹ 659",
                    discount_amount = "₹ 171",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/117/0.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-global-foyer-mall-gurgaon-690568",
                    is_chain = true,
                    is_prime = false
                ),
                JourneyStop(
                    id = 6,
                    title = "Punjab Grill Tappa",
                    address = "Shop 19, Ground floor, DLF Cybercity, Gurgaon-122002",
                    notes = "Had their famous chicken sandwich and beer.",
                    latitude = 28.4959442,
                    longitude = 77.0888396,
                    date = "Nov 06, 2025 at 02:42 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 3.2f,
                    durationAtStop = 75,
                    paid_amount = "₹ 2090",
                    total_amount = "₹ 3113",
                    discount_amount = "₹ 1023",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/643894/restaurant020210113062035.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/punjab-grill-tappa-cyber-hub-gurgaon-643894",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 7,
                    title = "OMI by Aldott",
                    address = "The Aldott, 81, Moulsari Ave, DLF Phase 3, Sector 24, Gurugram",
                    notes = "Walked at golden hour. Beautiful sunset view.",
                    latitude = 28.492682,
                    longitude = 77.1076935,
                    date = "Nov 05, 2025 at 04:23 PM",
                    stopType = StopType.VISIT,
                    distanceFromPrev = 4.1f,
                    durationAtStop = 60,
                    paid_amount = "₹ 1822",
                    total_amount = "₹ 2588",
                    discount_amount = "₹ 766",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/696057/restaurant020240607113245.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/omi-by-aldott-dlf-phase-3-gurgaon-696057",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 8,
                    title = "My Secret Place",
                    address = "SCO 14, Main Palam Vihar Road, Palam Vihar, Sector 23A, Gurugram",
                    notes = "Quick coffee stop before heading home.",
                    latitude = 28.5049246,
                    longitude = 77.0527208,
                    date = "Oct 10, 2025 at 11:29 PM",
                    stopType = StopType.REST,
                    distanceFromPrev = 9.8f,
                    durationAtStop = 25,
                    paid_amount = "₹ 752",
                    total_amount = "₹ 969",
                    discount_amount = "₹ 217",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/683100/restaurant020220329071556.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/my-secret-place-palam-vihar-gurgaon-683100",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 9,
                    title = "The Drunken Botanist",
                    address = "Unit 1B & 1C, Upper Ground Floor, Building 10C, Cyber Hub, Gurgaon",
                    notes = "Back home after an amazing day. Feet ache but memories made!",
                    latitude = 28.4938892,
                    longitude = 77.0883356,
                    date = "Jul 29, 2025 at 10:35 PM",
                    stopType = StopType.END,
                    distanceFromPrev = 1.8f,
                    durationAtStop = 0,
                    paid_amount = "₹ 5657",
                    total_amount = "₹ 7689",
                    discount_amount = "₹ 2032",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/653381/restaurant020180511132249.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/the-drunken-botanist-dlf-cyber-city-gurgaon-653381",
                    is_chain = false,
                    is_prime = false
                ),
            )
        ),

        // ── Journey 2: Delhi Heritage Walk ───────────────────────
        Journey(
            id = 2,
            name = "Delhi Heritage Walk",
            description = "Old Delhi to New Delhi monuments trail",
            date = "Jan 4, 2025",
            coverEmoji = "🏛️",
            totalDistanceKm = 22.4f,
            stops = listOf(
                JourneyStop(
                    id = 10, title = "Hotel – Connaught Place",
                    address = "Connaught Place, New Delhi 110001",
                    notes = "Checked out of hotel after breakfast.",
                    latitude = 28.6315, longitude = 77.2167,
                    stopType = StopType.START,
                    distanceFromPrev = 0f, durationAtStop = 10,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/117/0.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 11, title = "India Gate",
                    address = "Rajpath, India Gate, New Delhi 110001",
                    notes = "War memorial dedicated to soldiers. Grand structure.",
                    latitude = 28.6129, longitude = 77.2295,
                    stopType = StopType.PHOTO,
                    distanceFromPrev = 3.2f, durationAtStop = 40,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/687654/restaurant020230320081903.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = true
                ),
                JourneyStop(
                    id = 12, title = "Humayun's Tomb",
                    address = "Mathura Road, Nizamuddin East, New Delhi 110013",
                    notes = "Precursor to the Taj Mahal. Stunning Mughal architecture.",
                    latitude = 28.5933, longitude = 77.2507,
                    stopType = StopType.VISIT,
                    distanceFromPrev = 5.1f, durationAtStop = 75,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/552/menu020230111095005.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 13, title = "Paranthe Wali Gali",
                    address = "Chandni Chowk, Old Delhi, Delhi 110006",
                    notes = "Best stuffed parathas in India!",
                    latitude = 28.6562, longitude = 77.2310,
                    stopType = StopType.FOOD,
                    distanceFromPrev = 8.7f, durationAtStop = 50,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/695156/restaurant020240514121719.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 14, title = "Red Fort",
                    address = "Netaji Subhash Marg, Lal Qila, Old Delhi 110006",
                    notes = "Massive Mughal fortress. The Lahori Gate is breathtaking.",
                    latitude = 28.6562, longitude = 77.2410,
                    stopType = StopType.VISIT,
                    distanceFromPrev = 1.1f, durationAtStop = 90,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/643894/restaurant020210113062035.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 15, title = "Jama Masjid",
                    address = "Jama Masjid Road, Chandni Chowk, Old Delhi 110006",
                    notes = "One of the largest mosques in India.",
                    latitude = 28.6507, longitude = 77.2334,
                    stopType = StopType.PHOTO,
                    distanceFromPrev = 1.0f, durationAtStop = 45,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/696057/restaurant020240607113245.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 16, title = "Back to Hotel",
                    address = "Connaught Place, New Delhi 110001",
                    notes = "Exhausted but fulfilled. Covered 22km today!",
                    latitude = 28.6315, longitude = 77.2167,
                    stopType = StopType.END,
                    distanceFromPrev = 3.3f, durationAtStop = 0,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/683100/restaurant020220329071556.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                )
            )
        ),

        // ── Journey 3: Goa Beach Hopping ─────────────────────────
        Journey(
            id = 3,
            name = "Goa Beach Hopping",
            description = "North Goa beaches in one perfect day",
            date = "Feb 10, 2025",
            coverEmoji = "🏖️",
            totalDistanceKm = 48.2f,
            stops = listOf(
                JourneyStop(
                    id = 17, title = "Resort – Candolim",
                    address = "Candolim Beach Road, Candolim, Goa 403515",
                    notes = "Early start to beat the beach crowds.",
                    latitude = 15.5189, longitude = 73.7606,
                    stopType = StopType.START,
                    distanceFromPrev = 0f, durationAtStop = 10,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/117/0.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 18, title = "Aguada Fort",
                    address = "Sinquerim, Bardez, North Goa 403519",
                    notes = "17th century Portuguese fort. Stunning views of Arabian Sea.",
                    latitude = 15.5015, longitude = 73.7732,
                    stopType = StopType.PHOTO,
                    distanceFromPrev = 4.2f, durationAtStop = 45,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/687654/restaurant020230320081903.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 19, title = "Baga Beach",
                    address = "Baga, North Goa 403516",
                    notes = "Lively beach. Had fresh coconut water. Watched parasailing.",
                    latitude = 15.5556, longitude = 73.7519,
                    stopType = StopType.REST,
                    distanceFromPrev = 7.8f, durationAtStop = 60,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/552/menu020230111095005.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 20, title = "Brittos – Baga",
                    address = "Baga Beach Road, Baga, Goa 403516",
                    notes = "Famous beach shack. Had kingfish recheado and prawn curry rice.",
                    latitude = 15.5572, longitude = 73.7511,
                    stopType = StopType.FOOD,
                    distanceFromPrev = 0.3f, durationAtStop = 90,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/695156/restaurant020240514121719.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = true
                ),
                JourneyStop(
                    id = 21, title = "Anjuna Flea Market",
                    address = "Anjuna Beach, North Goa 403509",
                    notes = "Iconic flea market. Bought hand-painted bag and silver jewellery.",
                    latitude = 15.5736, longitude = 73.7403,
                    stopType = StopType.VISIT,
                    distanceFromPrev = 5.1f, durationAtStop = 75,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/643894/restaurant020210113062035.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 22, title = "Vagator Beach Sunset",
                    address = "Vagator, North Goa 403509",
                    notes = "Best sunset of the trip. Sat on the red cliffs as the sun dipped into the sea.",
                    latitude = 15.5996, longitude = 73.7440,
                    stopType = StopType.PHOTO,
                    distanceFromPrev = 4.6f, durationAtStop = 50,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/696057/restaurant020240607113245.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 23, title = "Thalassa – Vagator",
                    address = "Small Vagator Beach, Ozran, Goa 403509",
                    notes = "Greek taverna with sea view. Had Mediterranean mezze platter.",
                    latitude = 15.5981, longitude = 73.7446,
                    stopType = StopType.FOOD,
                    distanceFromPrev = 0.4f, durationAtStop = 75,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/683100/restaurant020220329071556.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                ),
                JourneyStop(
                    id = 24, title = "Resort – Candolim",
                    address = "Candolim Beach Road, Candolim, Goa 403515",
                    notes = "Long drive back. Stars were incredible on the way.",
                    latitude = 15.5189, longitude = 73.7606,
                    stopType = StopType.END,
                    distanceFromPrev = 25.8f, durationAtStop = 0,
                    date = "Jul 12, 2025 at 09:58 PM",
                    paid_amount = "₹ 288", total_amount = "₹ 404", discount_amount = "₹ 116",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/653381/restaurant020180511132249.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/delhi-ncr/haldirams-mg-road-delhi-119623",
                    is_chain = true, is_prime = false
                )
            )
        ),

        // ── Journey 4: Bangalore Food Trail ──────────────────────
        Journey(
            id = 4,
            name = "Bangalore Food Trail",
            description = "Best cafes and restaurants around Indiranagar & Koramangala",
            date = "Mar 5, 2025",
            coverEmoji = "🍽️",
            totalDistanceKm = 18.4f,
            stops = listOf(
                JourneyStop(
                    id = 25,
                    title = "Koshy's Bakery & Restaurant",
                    address = "39, St. Marks Road, Bangalore 560001",
                    notes = "Oldest cafe in Bangalore. Had their famous filter coffee and toast. Great morning start.",
                    latitude = 12.9716,
                    longitude = 77.5946,
                    date = "Mar 05, 2025 at 08:30 AM",
                    stopType = StopType.START,
                    distanceFromPrev = 0f,
                    durationAtStop = 45,
                    paid_amount = "₹ 320",
                    total_amount = "₹ 450",
                    discount_amount = "₹ 130",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/117/0.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/bangalore",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 26,
                    title = "CTR – Central Tiffin Room",
                    address = "7th Cross, Margosa Road, Malleshwaram, Bangalore 560003",
                    notes = "Famous for the crispiest benne masala dosa in the city. Queue was long but worth every minute.",
                    latitude = 12.9915,
                    longitude = 77.5686,
                    date = "Mar 05, 2025 at 10:00 AM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 3.8f,
                    durationAtStop = 60,
                    paid_amount = "₹ 180",
                    total_amount = "₹ 220",
                    discount_amount = "₹ 40",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/687654/restaurant020230320081903.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/bangalore",
                    is_chain = false,
                    is_prime = true
                ),
                JourneyStop(
                    id = 27,
                    title = "Toit Brewpub",
                    address = "298, 100 Feet Road, Indiranagar, Bangalore 560038",
                    notes = "Best craft beer in Bangalore! Had their Weiss and a wood-fired pizza. Rooftop was amazing.",
                    latitude = 12.9784,
                    longitude = 77.6408,
                    date = "Mar 05, 2025 at 01:00 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 4.2f,
                    durationAtStop = 90,
                    paid_amount = "₹ 1850",
                    total_amount = "₹ 2600",
                    discount_amount = "₹ 750",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/552/menu020230111095005.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/bangalore",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 28,
                    title = "Cubbon Park",
                    address = "Cubbon Park, Kasturba Road, Bangalore 560001",
                    notes = "Nice stroll through the park after a heavy lunch. Very peaceful and green.",
                    latitude = 12.9763,
                    longitude = 77.5929,
                    date = "Mar 05, 2025 at 03:00 PM",
                    stopType = StopType.REST,
                    distanceFromPrev = 2.9f,
                    durationAtStop = 40,
                    paid_amount = "₹ 0",
                    total_amount = "₹ 0",
                    discount_amount = "₹ 0",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/695156/restaurant020240514121719.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/bangalore",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 29,
                    title = "Truffles",
                    address = "Shop 4, Jyoti Nivas College Road, Koramangala, Bangalore 560034",
                    notes = "The OG burger place. Had their mushroom Swiss burger. Always a hit!",
                    latitude = 12.9344,
                    longitude = 77.6101,
                    date = "Mar 05, 2025 at 05:30 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 5.2f,
                    durationAtStop = 60,
                    paid_amount = "₹ 620",
                    total_amount = "₹ 890",
                    discount_amount = "₹ 270",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/643894/restaurant020210113062035.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/bangalore",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 30,
                    title = "The Black Pearl",
                    address = "80 Feet Road, Koramangala 4th Block, Bangalore 560034",
                    notes = "Great cocktails and live music on Friday nights. Perfect end to a great food day.",
                    latitude = 12.9352,
                    longitude = 77.6156,
                    date = "Mar 05, 2025 at 08:00 PM",
                    stopType = StopType.VISIT,
                    distanceFromPrev = 0.8f,
                    durationAtStop = 90,
                    paid_amount = "₹ 2200",
                    total_amount = "₹ 3100",
                    discount_amount = "₹ 900",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/696057/restaurant020240607113245.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/bangalore",
                    is_chain = false,
                    is_prime = true
                ),
                JourneyStop(
                    id = 31,
                    title = "Hotel – MG Road",
                    address = "MG Road, Bangalore 560001",
                    notes = "Back after an incredible food crawl. Bangalore never disappoints!",
                    latitude = 12.9758,
                    longitude = 77.6095,
                    date = "Mar 05, 2025 at 10:30 PM",
                    stopType = StopType.END,
                    distanceFromPrev = 1.5f,
                    durationAtStop = 0,
                    paid_amount = "₹ 0",
                    total_amount = "₹ 0",
                    discount_amount = "₹ 0",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/683100/restaurant020220329071556.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/bangalore",
                    is_chain = false,
                    is_prime = false
                )
            )
        ),

        // ── Journey 5: Jaipur Royal Dining ───────────────────────
        Journey(
            id = 5,
            name = "Jaipur Royal Dining",
            description = "A royal food and culture experience in the Pink City",
            date = "Apr 12, 2025",
            coverEmoji = "🏰",
            totalDistanceKm = 21.6f,
            stops = listOf(
                JourneyStop(
                    id = 32,
                    title = "Lassiwala",
                    address = "M.I. Road, Near Niro's Restaurant, Jaipur 302001",
                    notes = "Famous for the thickest, creamiest lassi in Rajasthan. Morning cup was absolutely divine.",
                    latitude = 26.9124,
                    longitude = 75.7873,
                    date = "Apr 12, 2025 at 09:00 AM",
                    stopType = StopType.START,
                    distanceFromPrev = 0f,
                    durationAtStop = 30,
                    paid_amount = "₹ 80",
                    total_amount = "₹ 80",
                    discount_amount = "₹ 0",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/117/0.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/jaipur",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 33,
                    title = "Hawa Mahal View Cafe",
                    address = "Near Hawa Mahal, Badi Chaupar, Jaipur 302002",
                    notes = "Had chai and poha while looking at Hawa Mahal. Perfect photo spot from the rooftop.",
                    latitude = 26.9239,
                    longitude = 75.8267,
                    date = "Apr 12, 2025 at 10:30 AM",
                    stopType = StopType.PHOTO,
                    distanceFromPrev = 3.1f,
                    durationAtStop = 45,
                    paid_amount = "₹ 220",
                    total_amount = "₹ 300",
                    discount_amount = "₹ 80",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/687654/restaurant020230320081903.jpeg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/jaipur",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 34,
                    title = "Rawat Mishthan Bhandar",
                    address = "Station Road, Near Railway Station, Jaipur 302006",
                    notes = "World famous pyaz kachori and mirchi bada. Had 3 servings — no regrets whatsoever.",
                    latitude = 26.9195,
                    longitude = 75.7882,
                    date = "Apr 12, 2025 at 12:00 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 2.8f,
                    durationAtStop = 40,
                    paid_amount = "₹ 160",
                    total_amount = "₹ 160",
                    discount_amount = "₹ 0",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/group/552/menu020230111095005.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/jaipur",
                    is_chain = false,
                    is_prime = true
                ),
                JourneyStop(
                    id = 35,
                    title = "1135 AD – Amber Fort",
                    address = "Amber Fort, Devisinghpura, Amer, Jaipur 302028",
                    notes = "Royal dining inside a 16th century fort. Had Laal Maas and Ker Sangri. Breathtaking ambience.",
                    latitude = 26.9855,
                    longitude = 75.8513,
                    date = "Apr 12, 2025 at 02:00 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 9.4f,
                    durationAtStop = 90,
                    paid_amount = "₹ 3200",
                    total_amount = "₹ 4800",
                    discount_amount = "₹ 1600",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/695156/restaurant020240514121719.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/jaipur",
                    is_chain = false,
                    is_prime = true
                ),
                JourneyStop(
                    id = 36,
                    title = "Johri Bazaar Street Food",
                    address = "Johri Bazaar, Jaipur 302003",
                    notes = "Walked through the jewellery market. Had gajak and ghewar from street stalls.",
                    latitude = 26.9198,
                    longitude = 75.8301,
                    date = "Apr 12, 2025 at 05:00 PM",
                    stopType = StopType.VISIT,
                    distanceFromPrev = 3.6f,
                    durationAtStop = 60,
                    paid_amount = "₹ 250",
                    total_amount = "₹ 250",
                    discount_amount = "₹ 0",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/643894/restaurant020210113062035.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/jaipur",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 37,
                    title = "Chokhi Dhani",
                    address = "Chokhi Dhani Village Resort, Tonk Road, Jaipur 303905",
                    notes = "Authentic Rajasthani thali experience. Folk dance, puppet show, and incredible dal baati churma.",
                    latitude = 26.8105,
                    longitude = 75.8216,
                    date = "Apr 12, 2025 at 07:30 PM",
                    stopType = StopType.FOOD,
                    distanceFromPrev = 2.7f,
                    durationAtStop = 120,
                    paid_amount = "₹ 1800",
                    total_amount = "₹ 2400",
                    discount_amount = "₹ 600",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/696057/restaurant020240607113245.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/jaipur",
                    is_chain = false,
                    is_prime = false
                ),
                JourneyStop(
                    id = 38,
                    title = "Hotel – Pink City",
                    address = "Sansar Chandra Road, Jaipur 302001",
                    notes = "What a day! Jaipur has the most royal food experience in India.",
                    latitude = 26.9124,
                    longitude = 75.7873,
                    date = "Apr 12, 2025 at 10:30 PM",
                    stopType = StopType.END,
                    distanceFromPrev = 0f,
                    durationAtStop = 0,
                    paid_amount = "₹ 0",
                    total_amount = "₹ 0",
                    discount_amount = "₹ 0",
                    image = "https://dt4l9bx31tioh.cloudfront.net/eazymedia/restaurant/653381/restaurant020180511132249.jpg?width=500&height=500&mode=fit",
                    restaurant_code = "https://www.eazydiner.com/jaipur",
                    is_chain = false,
                    is_prime = false
                )
            )
        )
    )
}